#!/usr/bin/python2
import sys, os

h_file = open("hal/regs.h", "w")
h_file.write( '/* regs.h is AUTOGENERATED. Do not edit. Change *.def instead. */\n' )
h_file.write( '#include <stdint.h>\n' )
h_file.write( '#ifndef SYS_REG_DEF_INCLUDED\n' )
h_file.write( '#define SYS_REG_DEF_INCLUDED\n' )
for filen in sys.argv[1:]:
    f = open(filen)

    h_file.write( "/****************************************************************\n" )
    h_file.write( " * File: %s\n" % filen )
    h_file.write( " ****************************************************************/\n" )

    for l in f:
        if len(l) > 0:
            if l.startswith('#'):
                continue
            arr = l.split()
            if (len(arr) > 2):
                name = arr[0]
                base = arr[1]
                size = arr[2]
            else:
                continue
            if (len(arr) > 4):
                desc = ' '.join(arr[3:])
            h_file.write( "/* %s - base addr: %s - len: %s */\n" % (desc, base, size) )
            if int(size) == 1:
                h_file.write( "#define SYSREG_%s ((uint32_t *)0x%08X)\n" % (name, int(base, 16)) )
            else:
                h_file.write( "#define SYSREG_%s_BASE ((uint32_t *)(0x%08x))\n" % (name, int(base, 16)) )
                h_file.write("#define SYSREG_%s(x) ((uint32_t *)(((uint32_t *)(SYSREG_%s_BASE)) + ((x))))\n\n" % (name, name));
            h_file.write("\n")

h_file.write( '#endif\n' )
