/* The file syscall_table.h is auto generated. DO NOT EDIT, CHANGES WILL BE LOST. */
/* If you want to add syscalls, use syscall_table_gen.py  */

#include "frosted.h"

#define SYS_SETCLOCK 			(0)
#define SYS_SLEEP 			(1)
#define SYS_SUSPEND 			(2)
#define SYS_THREAD_CREATE 			(3)
#define SYS_TEST 			(4)
#define SYS_GETPID 			(5)
#define SYS_GETPPID 			(6)
#define SYS_OPEN 			(7)
#define SYS_CLOSE 			(8)
#define SYS_READ 			(9)
#define SYS_WRITE 			(10)
#define SYS_SEEK 			(11)
#define SYS_MKDIR 			(12)
#define SYS_UNLINK 			(13)
#define SYS_GETTIMEOFDAY 			(14)
#define SYS_MALLOC 			(15)
#define SYS_FREE 			(16)
#define SYS_CALLOC 			(17)
#define SYS_REALLOC 			(18)
#define SYS_OPENDIR 			(19)
#define SYS_READDIR 			(20)
#define SYS_CLOSEDIR 			(21)
#define SYS_STAT 			(22)
#define SYS_POLL 			(23)
#define SYS_CHDIR 			(24)
#define SYS_GETCWD 			(25)
#define SYS_SEM_INIT 			(26)
#define SYS_SEM_POST 			(27)
#define SYS_SEM_WAIT 			(28)
#define SYS_SEM_DESTROY 			(29)
#define SYS_MUTEX_INIT 			(30)
#define SYS_MUTEX_UNLOCK 			(31)
#define SYS_MUTEX_LOCK 			(32)
#define SYS_MUTEX_DESTROY 			(33)
#define SYS_SOCKET 			(34)
#define SYS_KILL 			(35)
#define _SYSCALLS_NR 36
