#ifndef STM32F4_INCLUDE
#define STM32F4_INCLUDE
#define  CHIP_CLOCK_GPIOA              (0)
#define  CHIP_CLOCK_GPIOB              (1)
#define  CHIP_CLOCK_GPIOC              (2)   
#define  CHIP_CLOCK_GPIOD              (3)   
#define  CHIP_CLOCK_GPIOE              (4)   
#define  CHIP_CLOCK_GPIOF              (5)   
#define  CHIP_CLOCK_GPIOG              (6)   
#define  CHIP_CLOCK_GPIOH              (7)   
#define  CHIP_CLOCK_GPIOI              (8)   
#define  CHIP_CLOCK_CRC                (12)   
#define  CHIP_CLOCK_BKPSRAM            (18)   
#define  CHIP_CLOCK_CCMDATARAM         (20)   
#define  CHIP_CLOCK_DMA1               (21)   
#define  CHIP_CLOCK_DMA2               (22)   

#define  CHIP_CLOCK_ETHMAC             (25)   
#define  CHIP_CLOCK_ETHMACTX           (26)   
#define  CHIP_CLOCK_ETHMACRX           (27)   
#define  CHIP_CLOCK_ETHMACPTP          (28)   
#define  CHIP_CLOCK_OTGHS              (29)   
#define  CHIP_CLOCK_OTGHSULPI          (30)   

#define  CHIP_CLOCK_DCMI              (32)    
#define  CHIP_CLOCK_RNG               (38)    
#define  CHIP_CLOCK_OTGFS             (39)    

#define  CHIP_CLOCK_FSMC              (64)

#define  CHIP_CLOCK_TIM2              (160)
#define  CHIP_CLOCK_TIM3              (161)
#define  CHIP_CLOCK_TIM4              (162)
#define  CHIP_CLOCK_TIM5              (163)
#define  CHIP_CLOCK_TIM6              (164)
#define  CHIP_CLOCK_TIM7              (165)
#define  CHIP_CLOCK_TIM12             (166)
#define  CHIP_CLOCK_TIM13             (167)
#define  CHIP_CLOCK_TIM14             (168)
#define  CHIP_CLOCK_WWDG              (171)
#define  CHIP_CLOCK_SPI2              (174)
#define  CHIP_CLOCK_SPI3              (175)
#define  CHIP_CLOCK_USART2            (177)
#define  CHIP_CLOCK_USART3            (178)
#define  CHIP_CLOCK_UART4             (179)
#define  CHIP_CLOCK_UART5             (180)
#define  CHIP_CLOCK_I2C1              (181)
#define  CHIP_CLOCK_I2C2              (182)
#define  CHIP_CLOCK_I2C3              (183)
#define  CHIP_CLOCK_CAN1              (185)
#define  CHIP_CLOCK_CAN2              (186)
#define  CHIP_CLOCK_PWR               (188)
#define  CHIP_CLOCK_DAC               (189)

#define  CHIP_CLOCK_TIM1              (192)
#define  CHIP_CLOCK_TIM8              (193)
#define  CHIP_CLOCK_USART1            (196)
#define  CHIP_CLOCK_USART6            (197)
#define  CHIP_CLOCK_ADC1              (200)
#define  CHIP_CLOCK_ADC2              (201)
#define  CHIP_CLOCK_ADC3              (202)
#define  CHIP_CLOCK_SDIO              (203)
#define  CHIP_CLOCK_SPI1              (204)
#define  CHIP_CLOCK_SYSCFG            (206)
#define  CHIP_CLOCK_TIM9              (208)
#define  CHIP_CLOCK_TIM10             (209)
#define  CHIP_CLOCK_TIM11             (210)
#define  CHIP_CLOCK_SPI5              (212)
#define  CHIP_CLOCK_SPI6              (213)

#endif
