#ifndef IOCTL_INCLUDE
#define IOCTL_INCLUDE
#define IOCTL_GPIO_DISABLE 0
#define IOCTL_GPIO_ENABLE 1
#define IOCTL_GPIO_SET_OUTPUT 2
#define IOCTL_GPIO_SET_INPUT 3
#define IOCTL_GPIO_SET_MODE 4
#define IOCTL_GPIO_SET_FUNC 4
#endif
