#!/usr/bin/env bash

printf "\nSetting up Frosted qemu env...";
path="$(pwd)";

cd ~;

mkdir frosted-qemu
cd frosted-qemu;

sudo apt-get install build-essential cmake libusb-1.0 libusb-1.0.0-dev git screen

wget http://archive.trexotech.com:8081/arm-frosted-eabi-latest.tar.bz2;
tar xjf arm-frosted-eabi-latest.tar.bz2;
export PATH="$(pwd)/arm-frosted-eabi/bin:$PATH";

sudo apt-get build-dep qemu
git clone git://github.com/insane-adding-machines/qemu.git
cd qemu
./configure --prefix="$(pwd)/../qemu-bin" --target-list=arm-softmmu
make
make install
cd ..
export PATH="$(pwd)/qemu-bin/bin:$PATH"

cd "$path";

git submodule init;
git submodule update;
cd frosted-userland;
git submodule init;
git submodule update;


printf " OK!\n\nFrosted qemu env setup in ~/frosted-qemu\n\n";
