#ifndef IOCTL_INCLUDE
#define IOCTL_INCLUDE

/* GPIO */
#define IOCTL_GPIO_DISABLE 0
#define IOCTL_GPIO_ENABLE 1
#define IOCTL_GPIO_SET_OUTPUT 2
#define IOCTL_GPIO_SET_INPUT 3
#define IOCTL_GPIO_SET_PULLUPDOWN 4
#define IOCTL_GPIO_SET_ALT_FUNC 5

/* I2C */
#define IOCTL_I2C_SET_MASTER 0
#define IOCTL_I2C_SET_SLAVE  1
#define IOCTL_I2C_SET_ADDR7  2
#define IOCTL_I2C_SET_ADDR10 3
#define IOCTL_I2C_SET_ADDR7_2 4
#define IOCTL_I2C_SET_SPEED 5

/* L3GD20 */
#define IOCTL_L3GD20_WRITE_CTRL_REG     0
#define IOCTL_L3GD20_READ_CTRL_REG      1

#endif
