OBJS-y+= \
	board/$(BOARD)/src/stm32f4xx.o            \
	board/$(BOARD)/src/system_stm32f4xx.o     \
	family/$(FAMILY)/src/hardfault_debug.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_adc.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_adc_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_can.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_cortex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_crc.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_cryp.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_cryp_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_dac.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_dac_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_dcmi.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_dma2d.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_dma.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_dma_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_eth.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_flash.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_flash_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_gpio.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_hash.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_hash_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_hcd.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_i2c.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_i2c_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_i2s.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_i2s_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_irda.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_iwdg.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_ltdc.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_nand.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_nor.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_pccard.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_pcd.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_pwr.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_pwr_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_rcc.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_rcc_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_rng.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_rtc.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_rtc_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_sai.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_sd.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_sdram.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_smartcard.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_spi.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_sram.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_tim.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_tim_ex.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_uart.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_usart.o		\
	family/$(FAMILY)/src/stm32f4xx_hal_wwdg.o		\
	family/$(FAMILY)/src/stm32f4xx_ll_fmc.o		\
	family/$(FAMILY)/src/stm32f4xx_ll_fsmc.o		\
	family/$(FAMILY)/src/stm32f4xx_ll_sdmmc.o		\
	family/$(FAMILY)/src/stm32f4xx_ll_usb.o
